start: statements

statements: statements command
        | command

command: forward_cmd
        | rotate_cmd
        | penup_cmd
        | pendown_cmd
        | color_cmd
        | repeat_cmd

forward_cmd: "forward" NUMBER
rotate_cmd:  "rotate"  NUMBER
penup_cmd:   "penup"
pendown_cmd: "pendown"
color_cmd:   "color"   COLOR
repeat_cmd:  "repeat"  INT "{" statements "}"

COLOR: /[a-zA-Z]+/
COMMENT: /#[^\n]*/

%import common.NUMBER
%import common.INT
%import common.WS
%ignore WS
%ignore COMMENT