start: statements

statements: statements forwardCommand
        | statements rotateCommand
        | statements liftPenCommand
        | statements downPenCommand
        | statements changeColorCommand
        | statements repeatCommand
        | forwardCommand
        | rotateCommand
        | liftPenCommand
        | downPenCommand
        | changeColorCommand
        | repeatCommand

forwardCommand:
        "forward" NUMBER

rotateCommand:
        "rotate" NUMBER

liftPenCommand:
        "penup"

downPenCommand:
        "pendown"

changeColorCommand:
        "color" CNAME


repeatCommand: "repeat" NUMBER leftparen statements rightparen

leftparen: "("
rightparen: ")"

%import common.NUMBER
%import common.CNAME 
%import common.WS
%ignore WS