start: statements

statements: statement ";"
        | statements statement ";"

statement: assignment
        | expr

assignment: NAME "=" expr


expr: expr addop term
    | expr subop term
    | term

addop: "+"
subop: "-"

term: term multop factor
    | term divop factor
    | factor

multop: "*"
divop: "/"

factor: leftparen expr rightparen | NUMBER | NAME

leftparen: "("
rightparen: ")"

%import common.NUMBER
%import common.CNAME -> NAME
%import common.WS
%ignore WS